Module2 task1
htmlacademy-adaptive/2033165-mishka-26 pull request #2
Opened 2022-08-07 11:37 UTC by bakythaman

2022-08-08 14:26 UTC, DoberBober commented on source/catalog.html
> +          <img class="products-image" src="img/catalog-1.jpg" width="260" height="195" alt="Зайчик-попрыгайчик.">
Картинки оберни в ссылки.

2022-08-08 14:27 UTC, DoberBober commented on source/catalog.html
> +          <h3 class="products__title">Зайчик-попрыгайчик</h3>
Внутри заголовка тоже вставь ссылку.

2022-08-08 14:27 UTC, DoberBober commented on source/catalog.html
> +            <svg width="20" height="19" viewBox="0 0 20 19" fill="none" xmlns="http://www.w3.org/2000/svg">
Иконки корзины тоже оберни в ссылки.

2022-08-08 14:27 UTC, DoberBober commented on source/catalog.html
> +        <svg width="101" height="77" viewBox="0 0 101 77" fill="none" xmlns="http://www.w3.org/2000/svg">
Картинку вставь.

2022-08-08 14:28 UTC, DoberBober commented on source/catalog.html
> +      <button class="production__button button" type="button">СДелать заказ</button>
Ссылка.

2022-08-08 14:28 UTC, DoberBober commented on source/catalog.html
> +    <div class="main-footer__social social">
А где ссылка с лого?

2022-08-08 14:29 UTC, DoberBober commented on source/form.html
> +                <input class="form-group__input-text input" type="text" placeholder="Введите ваше имя*" name="name">
У всех инпутов со звёздочкой поставь required.

2022-08-08 14:30 UTC, DoberBober commented on source/form.html
> +      <form class="main-form">
action пропиши.

2022-08-08 14:30 UTC, DoberBober commented on source/index.html
> +          <h3 class="catalog-types-list__title">Предметы интерьера</h3>
Ссылки.

2022-08-08 14:31 UTC, DoberBober commented on source/index.html
> +          <button class="popular__submit button">ЗАКАЗАТЬ</button>
Сссылка.

2022-08-08 14:31 UTC, DoberBober commented on source/index.html
> +        <button class="feedback__submit button">Написать</button>
Ссылка.

2022-08-08 14:31 UTC, DoberBober commented on source/index.html
> +      <button class="contacts__submit button">НАпишите нам</button>
Ссылка.

2022-08-08 14:34 UTC, DoberBober requested changes
Есть небольшие правки.
Как поправишь, проверь БЭМ тут: https://yoksel.github.io/html-tree/
Слева вставляешь код, справа выделяет жёлтым ошибки.

2022-08-11 12:02 UTC, bakythaman commented on source/catalog.html
> +    <div class="main-footer__social social">
ты про HtmlAcademy? она же есть.

2022-08-11 12:17 UTC, DoberBober commented on source/catalog.html
> +    <div class="main-footer__social social">
Слева от соцсетей.
![image](https://user-images.githubusercontent.com/18398812/184131481-52e4d850-b71e-4bbe-a195-b456c7784a2d.png)

2022-08-11 12:42 UTC, merged